const now = new Date("2026-01-01T00:00:00.000Z");

const img = (id: string, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const fallbackDestinations = [
  {
    id: "dest_tokyo",
    slug: "tokyo",
    name: "东京",
    region: "关东",
    summary: "从设计街区、经典寺社到夜间美食，适合第一次来日本的高效率城市行程。",
    description:
      "东京适合把现代生活、传统街区和近郊自然放在同一份行程中。第一版内容重点覆盖浅草、银座、涩谷、新宿、丰洲、台场和箱根一日延伸。",
    season: "3-5 月赏樱、10-12 月城市漫游最舒适，冬季适合灯光活动和温泉延伸。",
    budgetMin: 900,
    budgetMax: 2600,
    coverImage: img("photo-1540959733332-eab4deabeeaf"),
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "dest_kyoto",
    slug: "kyoto",
    name: "京都",
    region: "关西",
    summary: "寺社、庭园、町家和季节风景密集，适合慢行与文化主题旅行。",
    description:
      "京都内容重点覆盖东山、岚山、伏见、锦市场和夜间花街，适合与大阪、奈良组合。",
    season: "3-4 月樱花、11 月红叶最受欢迎；夏季适合清晨寺社与夜间活动。",
    budgetMin: 800,
    budgetMax: 2400,
    coverImage: img("photo-1493976040374-85c8e12f0c0e"),
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "dest_osaka",
    slug: "osaka",
    name: "大阪",
    region: "关西",
    summary: "美食、购物、乐园和夜间城市体验集中，适合关西自由行的大本营。",
    description:
      "大阪适合做关西行程住宿中心，向京都、奈良、神户延伸，同时保留道顿堀、黑门市场、环球影城和梅田夜景。",
    season: "全年适合，3-5 月和 10-12 月体感最好；夏季适合乐园和夜间美食。",
    budgetMin: 780,
    budgetMax: 2200,
    coverImage: img("photo-1590559899731-a382839e5549"),
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "dest_sapporo",
    slug: "sapporo",
    name: "札幌",
    region: "北海道",
    summary: "雪景、海鲜、温泉和夏季花田，适合自然、自驾和家庭滑雪。",
    description:
      "札幌适合作为北海道行程入口，向小樽、富良野、登别和道东延伸。",
    season: "12-2 月雪季，6-8 月花田与自驾，9-10 月秋色清晰。",
    budgetMin: 950,
    budgetMax: 2800,
    coverImage: img("photo-1480796927426-f609979314bd"),
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "dest_okinawa",
    slug: "okinawa",
    name: "冲绳与那霸",
    region: "冲绳",
    summary: "海岛、琉球料理、亲子浮潜和轻松自驾。",
    description:
      "冲绳适合轻松海岛假期，组合那霸市区、恩纳村、古宇利岛和离岛浮潜。",
    season: "4-6 月和 10-11 月舒适，夏季适合海上活动但需留意台风。",
    budgetMin: 880,
    budgetMax: 2500,
    coverImage: img("photo-1507525428034-b723cf961d3e"),
    featured: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const fallbackPlaces = [
  {
    id: "place_asakusa",
    destinationId: "dest_tokyo",
    name: "浅草雷门",
    type: "景点",
    lat: 35.7111,
    lng: 139.7967,
    address: "东京都台东区浅草 2 丁目",
    tags: "寺社,老街,首次访日",
    summary: "东京传统街区入口，适合安排半日步行和小吃体验。",
  },
  {
    id: "place_shibuya",
    destinationId: "dest_tokyo",
    name: "涩谷十字路口",
    type: "城市地标",
    lat: 35.6595,
    lng: 139.7005,
    address: "东京都涩谷区道玄坂",
    tags: "夜景,购物,摄影",
    summary: "高密度城市夜景和商圈集合点。",
  },
  {
    id: "place_kiyomizu",
    destinationId: "dest_kyoto",
    name: "清水寺与二年坂",
    type: "文化区域",
    lat: 34.9949,
    lng: 135.785,
    address: "京都市东山区清水",
    tags: "寺社,步行,摄影",
    summary: "京都东山经典步行区域，适合清晨或傍晚安排。",
  },
  {
    id: "place_nishiki",
    destinationId: "dest_kyoto",
    name: "锦市场",
    type: "餐饮区域",
    lat: 35.005,
    lng: 135.7647,
    address: "京都市中京区锦小路通",
    tags: "美食,市场,购物",
    summary: "适合午间小吃和伴手礼采购。",
  },
  {
    id: "place_dotonbori",
    destinationId: "dest_osaka",
    name: "道顿堀",
    type: "餐饮区域",
    lat: 34.6687,
    lng: 135.5013,
    address: "大阪市中央区道顿堀",
    tags: "美食,夜景,购物",
    summary: "大阪夜间美食和霓虹街景核心区域。",
  },
  {
    id: "place_sapporo",
    destinationId: "dest_sapporo",
    name: "札幌市区",
    type: "城市区域",
    lat: 43.0618,
    lng: 141.3545,
    address: "北海道札幌市",
    tags: "海鲜,雪景,城市",
    summary: "北海道行程入口，适合市区美食和周边一日游。",
  },
  {
    id: "place_naha",
    destinationId: "dest_okinawa",
    name: "那霸国际通",
    type: "城市区域",
    lat: 26.2148,
    lng: 127.6792,
    address: "冲绳县那霸市",
    tags: "海岛,购物,琉球料理",
    summary: "冲绳城市入口，适合作为首晚和末晚停靠。",
  },
];

export const fallbackExperiences = [
  {
    id: "exp_tokyo_asakusa",
    destinationId: "dest_tokyo",
    placeId: "place_asakusa",
    slug: "tokyo-asakusa-old-town-walk",
    title: "浅草老街与隅田川半日漫游",
    summary: "用半天串联雷门、仲见世、观景点和隅田川散步。",
    description:
      "适合第一次到东京的旅客，节奏轻松，含传统街区讲解、甜点停靠和拍照点建议。",
    priceFrom: 360,
    durationHours: 4,
    difficulty: "轻松",
    language: "中文",
    includesMeal: false,
    cancellationPolicy: "出发前 48 小时可免费取消",
    rating: 4.8,
    reviewCount: 236,
    audience: "首次访日,家庭,情侣",
    themes: "文化,城市漫游,摄影",
    startTime: "09:30",
    meetingPoint: "浅草站 1 号出口",
    restrictions: "需步行约 4 公里，雨天照常出发。",
    includes: "中文向导,路线说明,小吃推荐清单",
    excludes: "餐饮,个人购物,交通费",
    coverImage: img("photo-1528164344705-47542687000d"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_tokyo_shibuya",
    destinationId: "dest_tokyo",
    placeId: "place_shibuya",
    slug: "tokyo-shibuya-night-food",
    title: "涩谷夜间美食与隐藏小巷",
    summary: "从涩谷夜景到居酒屋小巷，适合晚到东京的第一晚。",
    description: "路线控制在步行友好的范围内，重点体验拉面、串烧、甜品和城市夜景。",
    priceFrom: 520,
    durationHours: 3.5,
    difficulty: "轻松",
    language: "中文",
    includesMeal: true,
    cancellationPolicy: "出发前 24 小时可改期一次",
    rating: 4.7,
    reviewCount: 188,
    audience: "朋友,情侣,美食爱好者",
    themes: "美食,夜景,城市漫游",
    startTime: "18:30",
    meetingPoint: "涩谷站八公像附近",
    restrictions: "未满 20 岁不含酒精饮品。",
    includes: "向导,3 站小食,一杯软饮",
    excludes: "额外点单,酒店接送",
    coverImage: img("photo-1503899036084-c55cdd92da26"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_kyoto_higashiyama",
    destinationId: "dest_kyoto",
    placeId: "place_kiyomizu",
    slug: "kyoto-higashiyama-morning",
    title: "东山清晨寺社步行",
    summary: "避开拥挤时段，串联清水寺、二年坂与石塀小路。",
    description: "清晨出发，保留安静拍照时间，讲解京都街区肌理与参拜礼仪。",
    priceFrom: 460,
    durationHours: 4,
    difficulty: "中等",
    language: "中文",
    includesMeal: false,
    cancellationPolicy: "出发前 48 小时可免费取消",
    rating: 4.9,
    reviewCount: 211,
    audience: "文化爱好者,情侣,摄影",
    themes: "文化,摄影,寺社",
    startTime: "07:30",
    meetingPoint: "清水五条站",
    restrictions: "坡道较多，需穿舒适鞋。",
    includes: "中文向导,路线说明,参拜礼仪",
    excludes: "门票,餐饮,交通",
    coverImage: img("photo-1524413840807-0c3cb6fa808d"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_kyoto_nishiki",
    destinationId: "dest_kyoto",
    placeId: "place_nishiki",
    slug: "kyoto-nishiki-market-food",
    title: "锦市场与京都厨房小吃",
    summary: "用半日理解京都食材、小吃和伴手礼采购动线。",
    description: "适合美食主题行程，串联锦市场、河原町和几家本地小店。",
    priceFrom: 520,
    durationHours: 3,
    difficulty: "轻松",
    language: "中文",
    includesMeal: true,
    cancellationPolicy: "出发前 24 小时可免费取消",
    rating: 4.8,
    reviewCount: 164,
    audience: "美食爱好者,家庭,朋友",
    themes: "美食,市场,文化",
    startTime: "10:30",
    meetingPoint: "四条站",
    restrictions: "市场拥挤时需排队。",
    includes: "向导,3 站小食,采购建议",
    excludes: "额外餐饮,交通费",
    coverImage: img("photo-1554797589-7241bb691973"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_osaka_dotonbori",
    destinationId: "dest_osaka",
    placeId: "place_dotonbori",
    slug: "osaka-dotonbori-night-food",
    title: "道顿堀与难波夜间美食",
    summary: "大阪第一晚的高效率美食路线，串联章鱼烧、串炸和霓虹街景。",
    description: "适合想轻松进入大阪节奏的旅客，保留拍照点、排队策略和夜宵选择。",
    priceFrom: 540,
    durationHours: 3.5,
    difficulty: "轻松",
    language: "中文",
    includesMeal: true,
    cancellationPolicy: "出发前 24 小时可免费取消",
    rating: 4.8,
    reviewCount: 198,
    audience: "朋友,情侣,美食爱好者",
    themes: "美食,夜景,城市漫游",
    startTime: "18:00",
    meetingPoint: "难波站",
    restrictions: "未满 20 岁不含酒精饮品。",
    includes: "向导,3 站小食,夜景路线",
    excludes: "额外点单,酒店接送",
    coverImage: img("photo-1504674900247-0877df9cc836"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_osaka_usj",
    destinationId: "dest_osaka",
    placeId: "place_dotonbori",
    slug: "osaka-usj-planning",
    title: "大阪环球影城一日规划",
    summary: "根据同行人群安排入园时间、热门项目顺序和晚间回城路线。",
    description: "不含门票代订，重点提供动线、餐厅、亲子和快速通行券使用建议。",
    priceFrom: 380,
    durationHours: 2,
    difficulty: "轻松",
    language: "中文",
    includesMeal: false,
    cancellationPolicy: "出发前 48 小时可免费取消",
    rating: 4.6,
    reviewCount: 92,
    audience: "家庭,朋友,主题乐园",
    themes: "乐园,亲子,规划",
    startTime: "20:00",
    meetingPoint: "线上规划",
    restrictions: "不保证园区库存和排队时间。",
    includes: "中文规划,动线表,交通建议",
    excludes: "门票,餐饮,交通费",
    coverImage: img("photo-1590253230532-a67f6bc61c9e"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_sapporo_seafood",
    destinationId: "dest_sapporo",
    placeId: "place_sapporo",
    slug: "sapporo-seafood-snow",
    title: "札幌海鲜市场与雪景半日",
    summary: "安排二条市场、札幌钟楼和大通公园雪景动线。",
    description: "适合冬季抵达札幌后的轻松半日，兼顾海鲜早餐和城市散步。",
    priceFrom: 580,
    durationHours: 4,
    difficulty: "轻松",
    language: "中文",
    includesMeal: true,
    cancellationPolicy: "出发前 48 小时可免费取消",
    rating: 4.7,
    reviewCount: 119,
    audience: "家庭,朋友,美食爱好者",
    themes: "雪景,美食,城市漫游",
    startTime: "09:00",
    meetingPoint: "札幌站",
    restrictions: "雪季路面湿滑，需保暖。",
    includes: "向导,市场讲解,热饮建议",
    excludes: "餐费,交通费",
    coverImage: img("photo-1519681393784-d120267933ba"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "exp_okinawa_naha",
    destinationId: "dest_okinawa",
    placeId: "place_naha",
    slug: "okinawa-naha-ryukyu-food",
    title: "那霸国际通与琉球料理",
    summary: "用一晚熟悉那霸市区、琉球料理和伴手礼动线。",
    description: "适合冲绳首晚或末晚，节奏轻松，兼顾晚餐和购物。",
    priceFrom: 460,
    durationHours: 3,
    difficulty: "轻松",
    language: "中文",
    includesMeal: true,
    cancellationPolicy: "出发前 24 小时可免费取消",
    rating: 4.7,
    reviewCount: 86,
    audience: "家庭,朋友,情侣",
    themes: "海岛,美食,购物",
    startTime: "18:00",
    meetingPoint: "县厅前站",
    restrictions: "旺季餐厅需提前预约。",
    includes: "向导,餐厅建议,购物路线",
    excludes: "餐费,交通费",
    coverImage: img("photo-1500375592092-40eb2168fd21"),
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const fallbackRouteTemplates = [
  {
    id: "route_tokyo_3d",
    destinationId: "dest_tokyo",
    title: "东京初访 3 日",
    slug: "tokyo-first-visit-3-days",
    summary: "浅草、涩谷、丰洲、银座与箱根延伸的经典组合。",
    days: 3,
    budget: 4200,
    themes: "首次访日,美食,城市",
    heroImage: img("photo-1513407030348-c983a97b98d8"),
    stops: "浅草,涩谷,丰洲市场,银座,箱根",
  },
  {
    id: "route_kansai_5d",
    destinationId: "dest_osaka",
    title: "关西美食文化 5 日",
    slug: "kansai-food-culture-5-days",
    summary: "大阪住宿，串联京都、奈良和大阪夜间美食。",
    days: 5,
    budget: 6200,
    themes: "关西,美食,文化",
    heroImage: img("photo-1478436127897-769e1b3f0f36"),
    stops: "大阪,京都,奈良,道顿堀",
  },
  {
    id: "route_hokkaido_4d",
    destinationId: "dest_sapporo",
    title: "北海道雪景 4 日",
    slug: "hokkaido-winter-4-days",
    summary: "札幌、小樽和温泉雪景组合。",
    days: 4,
    budget: 6800,
    themes: "雪景,温泉,海鲜",
    heroImage: img("photo-1480796927426-f609979314bd"),
    stops: "札幌,小樽,登别",
  },
];

export const fallbackReviewLinks = [
  {
    id: "review_google",
    ownerType: "experience",
    ownerId: "exp_tokyo_asakusa",
    provider: "Google Maps",
    rating: 4.7,
    url: "https://www.google.com/maps",
  },
  {
    id: "review_tripadvisor",
    ownerType: "experience",
    ownerId: "exp_osaka_dotonbori",
    provider: "Tripadvisor",
    rating: 4.6,
    url: "https://www.tripadvisor.com/",
  },
];
