import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL || "file:./prisma/dev.db",
});
const prisma = new PrismaClient({ adapter });

const img = (id: string, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const destinations = [
  {
    slug: "tokyo",
    name: "东京",
    region: "关东",
    summary: "从设计街区、经典寺社到夜间美食，适合第一次来日本的高效率城市行程。",
    description:
      "东京适合把现代生活、传统街区和近郊自然放在同一份行程中。第一版内容重点覆盖浅草、银座、涩谷、新宿、丰洲、台场和箱根一日延伸。",
    season: "3-5 月赏樱、10-12 月城市漫游最舒适，冬季适合灯光活动和温泉延伸。",
    budgetMin: 900,
    budgetMax: 2600,
    coverImage: img("photo-1540959733332-eab4deabeeaf"),
    featured: true,
    places: [
      {
        key: "asakusa",
        name: "浅草雷门",
        type: "景点",
        lat: 35.7111,
        lng: 139.7967,
        address: "东京都台东区浅草 2 丁目",
        tags: "寺社,老街,首次访日",
        summary: "东京传统街区入口，适合安排半日步行和小吃体验。",
      },
      {
        key: "shibuya",
        name: "涩谷十字路口",
        type: "城市地标",
        lat: 35.6595,
        lng: 139.7005,
        address: "东京都涩谷区道玄坂",
        tags: "夜景,购物,摄影",
        summary: "高密度城市夜景和商圈集合点。",
      },
      {
        key: "toyusu",
        name: "丰洲市场",
        type: "餐饮区域",
        lat: 35.6432,
        lng: 139.7881,
        address: "东京都江东区丰洲 6 丁目",
        tags: "海鲜,市场,早餐",
        summary: "适合安排清晨海鲜早餐和市场参观。",
      },
    ],
    experiences: [
      {
        slug: "tokyo-asakusa-old-town-walk",
        title: "浅草老街与隅田川半日漫游",
        placeKey: "asakusa",
        summary: "用半天串联雷门、仲见世、观景点和隅田川散步。",
        description:
          "适合第一次到东京的旅客，节奏轻松，含传统街区讲解、甜点停靠和拍照点建议。",
        priceFrom: 360,
        durationHours: 4,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 48 小时可免费取消",
        rating: 4.8,
        reviewCount: 236,
        audience: "首次访日,家庭,情侣",
        themes: "文化,城市漫游,摄影",
        startTime: "09:30",
        meetingPoint: "浅草站 1 号出口",
        restrictions: "需步行约 4 公里，雨天照常出发。",
        includes: "中文向导,路线说明,小吃推荐清单",
        excludes: "餐饮,个人购物,交通费",
        coverImage: img("photo-1528164344705-47542687000d"),
      },
      {
        slug: "tokyo-shibuya-night-food",
        title: "涩谷夜间美食与隐藏小巷",
        placeKey: "shibuya",
        summary: "从涩谷夜景到居酒屋小巷，适合晚到东京的第一晚。",
        description:
          "路线控制在步行友好的范围内，重点体验拉面、串烧、甜品和城市夜景。",
        priceFrom: 520,
        durationHours: 3.5,
        difficulty: "轻松",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 24 小时可改期一次",
        rating: 4.7,
        reviewCount: 188,
        audience: "朋友,情侣,美食爱好者",
        themes: "美食,夜景,城市漫游",
        startTime: "18:30",
        meetingPoint: "涩谷站八公像附近",
        restrictions: "未满 20 岁不含酒精饮品。",
        includes: "向导,3 站小食,一杯软饮",
        excludes: "额外点单,酒店接送",
        coverImage: img("photo-1503899036084-c55cdd92da26"),
      },
      {
        slug: "tokyo-toyosu-sushi-market",
        title: "丰洲市场海鲜早餐与寿司入门",
        placeKey: "toyusu",
        summary: "清晨参观市场动线，理解寿司点单和鱼类季节。",
        description:
          "适合美食主题行程，安排市场楼层导览、早餐建议和台场延伸路线。",
        priceFrom: 680,
        durationHours: 4,
        difficulty: "中等",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 48 小时可免费取消",
        rating: 4.9,
        reviewCount: 143,
        audience: "美食爱好者,家庭,小团",
        themes: "美食,市场,文化",
        startTime: "07:00",
        meetingPoint: "市场前站检票口",
        restrictions: "需早起，部分店铺可能排队。",
        includes: "市场导览,早餐预算建议,点单翻译卡",
        excludes: "餐费实报实销,交通费",
        coverImage: img("photo-1553621042-f6e147245754"),
      },
      {
        slug: "tokyo-design-shopping-day",
        title: "表参道与银座设计购物路线",
        placeKey: "shibuya",
        summary: "精选设计店、生活方式品牌和百货退税动线。",
        description:
          "路线适合想高效购物但不想只逛大商场的旅客，含咖啡停靠和行李寄存建议。",
        priceFrom: 420,
        durationHours: 5,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.6,
        reviewCount: 97,
        audience: "情侣,朋友,设计爱好者",
        themes: "购物,设计,城市漫游",
        startTime: "11:00",
        meetingPoint: "表参道站 A2 出口",
        restrictions: "不代购、不保证库存。",
        includes: "路线策划,退税说明,咖啡店清单",
        excludes: "购物费用,餐饮",
        coverImage: img("photo-1492571350019-22de08371fd3"),
      },
      {
        slug: "tokyo-hakone-onsen-day",
        title: "箱根温泉与富士山远眺一日",
        placeKey: "asakusa",
        summary: "从东京出发的一日温泉延伸，适合想加入自然休息日的行程。",
        description:
          "包含交通方案建议、温泉礼仪说明、芦之湖和观景点选择，按天气动态调整。",
        priceFrom: 980,
        durationHours: 10,
        difficulty: "中等",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 72 小时可免费取消",
        rating: 4.7,
        reviewCount: 121,
        audience: "家庭,情侣,温泉爱好者",
        themes: "温泉,自然,近郊",
        startTime: "08:00",
        meetingPoint: "新宿站西口",
        restrictions: "纹身入浴需提前确认，天气会影响富士山可见度。",
        includes: "行程顾问,交通说明,温泉礼仪说明",
        excludes: "铁路票,温泉门票,餐饮",
        coverImage: img("photo-1576675466969-38eeae4b41f6"),
      },
    ],
    routes: [
      {
        slug: "tokyo-first-visit-3-days",
        title: "东京初访 3 日",
        summary: "浅草、涩谷、丰洲、银座与箱根延伸的经典组合。",
        days: 3,
        budget: 4200,
        themes: "首次访日,美食,城市",
        heroImage: img("photo-1513407030348-c983a97b98d8"),
        stops: "浅草,涩谷,丰洲市场,银座,箱根",
      },
    ],
  },
  {
    slug: "kyoto",
    name: "京都",
    region: "关西",
    summary: "寺社、庭园、町家和季节风景密集，适合慢行与文化主题旅行。",
    description:
      "京都内容重点覆盖东山、岚山、伏见、锦市场和夜间花街，适合与大阪、奈良组合。",
    season: "3-4 月樱花、11 月红叶最受欢迎；夏季适合清晨寺社与夜间活动。",
    budgetMin: 800,
    budgetMax: 2400,
    coverImage: img("photo-1493976040374-85c8e12f0c0e"),
    featured: true,
    places: [
      {
        key: "kiyomizu",
        name: "清水寺与二年坂",
        type: "文化区域",
        lat: 34.9949,
        lng: 135.785,
        address: "京都市东山区清水",
        tags: "寺社,步行,摄影",
        summary: "京都东山经典步行区域，适合清晨或傍晚安排。",
      },
      {
        key: "arashiyama",
        name: "岚山",
        type: "自然区域",
        lat: 35.0094,
        lng: 135.6675,
        address: "京都市右京区嵯峨",
        tags: "竹林,河岸,自然",
        summary: "自然与寺院结合的半日或一日路线。",
      },
      {
        key: "nishiki",
        name: "锦市场",
        type: "餐饮区域",
        lat: 35.005,
        lng: 135.7647,
        address: "京都市中京区锦小路通",
        tags: "美食,市场,购物",
        summary: "适合午间小吃和伴手礼采购。",
      },
    ],
    experiences: [
      {
        slug: "kyoto-higashiyama-morning",
        title: "东山清晨寺社步行",
        placeKey: "kiyomizu",
        summary: "避开拥挤时段，串联清水寺、二年坂与石塀小路。",
        description:
          "清晨出发，保留安静拍照时间，讲解京都街区肌理与参拜礼仪。",
        priceFrom: 460,
        durationHours: 4,
        difficulty: "中等",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 48 小时可免费取消",
        rating: 4.9,
        reviewCount: 211,
        audience: "文化爱好者,情侣,摄影",
        themes: "文化,摄影,寺社",
        startTime: "07:30",
        meetingPoint: "清水五条站",
        restrictions: "坡道较多，需穿舒适鞋。",
        includes: "中文向导,路线说明,参拜礼仪",
        excludes: "门票,餐饮,交通",
        coverImage: img("photo-1524413840807-0c3cb6fa808d"),
      },
      {
        slug: "kyoto-arashiyama-river",
        title: "岚山竹林与保津川慢行",
        placeKey: "arashiyama",
        summary: "竹林、河岸、庭园与茶点停靠的半日路线。",
        description:
          "适合把自然景色放进行程中，路线避开纯打卡，保留河岸散步和茶店时间。",
        priceFrom: 520,
        durationHours: 5,
        difficulty: "中等",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 48 小时可免费取消",
        rating: 4.7,
        reviewCount: 156,
        audience: "家庭,情侣,自然爱好者",
        themes: "自然,文化,摄影",
        startTime: "08:30",
        meetingPoint: "岚山站",
        restrictions: "旺季人流较大，路线会按现场调整。",
        includes: "向导,庭园路线建议,茶点店清单",
        excludes: "门票,餐饮",
        coverImage: img("photo-1493997181344-712f2f19d87a"),
      },
      {
        slug: "kyoto-nishiki-food",
        title: "锦市场与京都厨房小吃",
        placeKey: "nishiki",
        summary: "用小吃理解京都食材、酱菜、甜点与伴手礼。",
        description:
          "适合午间安排，包含点单翻译、预算控制和周边咖啡甜点延伸。",
        priceFrom: 390,
        durationHours: 3,
        difficulty: "轻松",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.6,
        reviewCount: 134,
        audience: "美食爱好者,家庭,朋友",
        themes: "美食,市场,购物",
        startTime: "11:00",
        meetingPoint: "四条站",
        restrictions: "部分摊位仅收现金。",
        includes: "向导,3 份试吃,伴手礼建议",
        excludes: "额外餐饮,个人购物",
        coverImage: img("photo-1554797589-7241bb691973"),
      },
      {
        slug: "kyoto-night-gion",
        title: "祇园夜间町家与花街散步",
        placeKey: "kiyomizu",
        summary: "夜间步行理解花街礼仪、町家街景与安静巷弄。",
        description:
          "不追逐拍摄艺伎，重点是街区礼仪、建筑和夜间摄影点。",
        priceFrom: 450,
        durationHours: 2.5,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 24 小时可改期一次",
        rating: 4.8,
        reviewCount: 102,
        audience: "情侣,文化爱好者,摄影",
        themes: "文化,夜景,摄影",
        startTime: "19:00",
        meetingPoint: "祇园四条站",
        restrictions: "请遵守当地拍摄规定。",
        includes: "向导,夜间路线,礼仪说明",
        excludes: "餐饮,交通",
        coverImage: img("photo-1526481280693-3bfa7568e0f3"),
      },
    ],
    routes: [
      {
        slug: "kyoto-slow-culture-3-days",
        title: "京都慢行文化 3 日",
        summary: "东山清晨、岚山自然、锦市场和祇园夜色的平衡路线。",
        days: 3,
        budget: 3600,
        themes: "文化,自然,美食",
        heroImage: img("photo-1478436127897-769e1b3f0f36"),
        stops: "清水寺,二年坂,岚山,锦市场,祇园",
      },
    ],
  },
  {
    slug: "osaka",
    name: "大阪",
    region: "关西",
    summary: "美食、购物、主题乐园和关西交通枢纽，适合作为大阪京都奈良组合的基地。",
    description:
      "大阪第一版覆盖难波、道顿堀、新世界、大阪城和环球影城周边，强调美食和高效率交通。",
    season: "全年适合，春秋天气最好；夏季夜间美食和室内活动更舒服。",
    budgetMin: 700,
    budgetMax: 2200,
    coverImage: img("photo-1590559899731-a382839e5549"),
    featured: true,
    places: [
      {
        key: "dotonbori",
        name: "道顿堀",
        type: "美食区域",
        lat: 34.6687,
        lng: 135.5013,
        address: "大阪市中央区道顿堀",
        tags: "美食,夜景,购物",
        summary: "大阪夜间美食和霓虹招牌密集区域。",
      },
      {
        key: "osaka-castle",
        name: "大阪城公园",
        type: "景点",
        lat: 34.6873,
        lng: 135.5262,
        address: "大阪市中央区大阪城",
        tags: "历史,公园,亲子",
        summary: "适合半日历史与公园散步。",
      },
    ],
    experiences: [
      {
        slug: "osaka-dotonbori-food-crawl",
        title: "道顿堀与难波夜间美食",
        placeKey: "dotonbori",
        summary: "章鱼烧、串炸、拉面和居酒屋入门路线。",
        description:
          "适合抵达大阪后的第一晚，用短距离步行理解大阪美食节奏。",
        priceFrom: 480,
        durationHours: 3,
        difficulty: "轻松",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.8,
        reviewCount: 244,
        audience: "朋友,情侣,美食爱好者",
        themes: "美食,夜景,城市漫游",
        startTime: "18:00",
        meetingPoint: "难波站 14 号出口",
        restrictions: "未满 20 岁不含酒精饮品。",
        includes: "向导,3 站小吃,点单翻译",
        excludes: "额外点单,交通",
        coverImage: img("photo-1589452271712-64b8a66c7b71"),
      },
      {
        slug: "osaka-castle-history",
        title: "大阪城历史与水上巴士半日",
        placeKey: "osaka-castle",
        summary: "大阪城、公园和水边城市视角的半日安排。",
        description:
          "适合家庭和第一次到大阪的旅客，兼顾历史、散步和轻松交通。",
        priceFrom: 430,
        durationHours: 4,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 48 小时可免费取消",
        rating: 4.6,
        reviewCount: 88,
        audience: "家庭,首次访日,历史爱好者",
        themes: "历史,亲子,城市",
        startTime: "09:30",
        meetingPoint: "森之宫站",
        restrictions: "水上巴士受天气和班次影响。",
        includes: "向导,历史说明,交通建议",
        excludes: "门票,船票,餐饮",
        coverImage: img("photo-1590253230532-a67f6bc61c9e"),
      },
      {
        slug: "osaka-usj-planning",
        title: "环球影城前置规划与周边动线",
        placeKey: "dotonbori",
        summary: "按同行人群规划入园顺序、交通和用餐窗口。",
        description:
          "不含门票，重点帮助用户在出发前规划快速票、热门项目和回程交通。",
        priceFrom: 260,
        durationHours: 1.5,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.5,
        reviewCount: 67,
        audience: "家庭,朋友,主题乐园",
        themes: "主题乐园,亲子,规划",
        startTime: "20:00",
        meetingPoint: "线上会议",
        restrictions: "不代购门票，库存以官方为准。",
        includes: "路线规划,项目顺序建议,交通建议",
        excludes: "门票,快速票,餐饮",
        coverImage: img("photo-1549944850-84e00be4203b"),
      },
      {
        slug: "osaka-market-kitchen",
        title: "黑门市场与家庭料理体验",
        placeKey: "dotonbori",
        summary: "市场采购后学习一餐适合家庭复刻的大阪料理。",
        description:
          "从食材挑选到简易料理，适合希望加入互动体验的小团。",
        priceFrom: 760,
        durationHours: 4.5,
        difficulty: "中等",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 72 小时可免费取消",
        rating: 4.9,
        reviewCount: 74,
        audience: "家庭,朋友,美食爱好者",
        themes: "美食,体验,市场",
        startTime: "10:00",
        meetingPoint: "日本桥站",
        restrictions: "需提前告知过敏源。",
        includes: "食材,料理指导,午餐",
        excludes: "交通,额外饮品",
        coverImage: img("photo-1504674900247-0877df9cc836"),
      },
    ],
    routes: [
      {
        slug: "osaka-food-family-2-days",
        title: "大阪美食亲子 2 日",
        summary: "夜间美食、大阪城和主题乐园规划的轻松组合。",
        days: 2,
        budget: 2800,
        themes: "美食,亲子,城市",
        heroImage: img("photo-1590559899731-a382839e5549"),
        stops: "道顿堀,大阪城,黑门市场,环球影城周边",
      },
    ],
  },
  {
    slug: "sapporo",
    name: "札幌与北海道",
    region: "北海道",
    summary: "雪景、温泉、海鲜和夏季花田，适合自然、美食和自驾主题。",
    description:
      "北海道第一版以札幌为入口，覆盖小樽、定山溪、富良野和海鲜市场，适合四季路线。",
    season: "12-2 月雪景，6-8 月花田与自驾，9-10 月秋色和海鲜。",
    budgetMin: 1000,
    budgetMax: 3000,
    coverImage: img("photo-1480796927426-f609979314bd"),
    featured: false,
    places: [
      {
        key: "otaru",
        name: "小樽运河",
        type: "近郊",
        lat: 43.1998,
        lng: 141.0007,
        address: "北海道小樽市港町",
        tags: "运河,玻璃,甜点",
        summary: "札幌近郊一日经典目的地。",
      },
      {
        key: "sapporo-market",
        name: "札幌二条市场",
        type: "餐饮区域",
        lat: 43.0601,
        lng: 141.3572,
        address: "札幌市中央区南 3 条东",
        tags: "海鲜,市场,早餐",
        summary: "适合海鲜早餐和城市散步组合。",
      },
    ],
    experiences: [
      {
        slug: "sapporo-seafood-market",
        title: "札幌海鲜市场早餐",
        placeKey: "sapporo-market",
        summary: "二条市场点单、海鲜季节和周边咖啡路线。",
        description: "适合北海道第一天上午安排，轻松理解海胆、蟹和海鲜丼点单。",
        priceFrom: 420,
        durationHours: 2.5,
        difficulty: "轻松",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.7,
        reviewCount: 91,
        audience: "美食爱好者,家庭",
        themes: "美食,市场,城市",
        startTime: "08:30",
        meetingPoint: "大通站",
        restrictions: "市场价格随季节浮动。",
        includes: "向导,点单翻译,早餐预算建议",
        excludes: "餐费实报实销,交通",
        coverImage: img("photo-1559339352-11d035aa65de"),
      },
      {
        slug: "otaru-canal-sweet-walk",
        title: "小樽运河与甜点散步",
        placeKey: "otaru",
        summary: "运河、玻璃工房、音乐盒和甜点店的近郊一日。",
        description:
          "从札幌出发，适合不自驾旅客，用公共交通完成轻松一日。",
        priceFrom: 620,
        durationHours: 7,
        difficulty: "中等",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 48 小时可免费取消",
        rating: 4.8,
        reviewCount: 112,
        audience: "情侣,家庭,摄影",
        themes: "近郊,甜点,摄影",
        startTime: "09:00",
        meetingPoint: "札幌站西口",
        restrictions: "冬季路面湿滑，需防滑鞋。",
        includes: "行程向导,铁路换乘说明,甜点清单",
        excludes: "交通,餐饮,购物",
        coverImage: img("photo-1518098268026-4e89f1a2cd8e"),
      },
      {
        slug: "hokkaido-furano-flower-day",
        title: "富良野花田与乡野摄影",
        placeKey: "otaru",
        summary: "夏季花田、农场甜品和乡野景观路线。",
        description:
          "适合 6-8 月北海道行程，按花期调整停靠点，提供自驾和包车两套方案。",
        priceFrom: 1280,
        durationHours: 10,
        difficulty: "中等",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 72 小时可免费取消",
        rating: 4.8,
        reviewCount: 59,
        audience: "摄影,家庭,自然爱好者",
        themes: "自然,摄影,季节",
        startTime: "08:00",
        meetingPoint: "札幌站北口",
        restrictions: "花期受天气影响，行程需预留弹性。",
        includes: "路线规划,花期建议,停车点说明",
        excludes: "车辆,油费,餐饮",
        coverImage: img("photo-1500530855697-b586d89ba3ee"),
      },
      {
        slug: "jozankei-onsen-snow",
        title: "定山溪温泉与冬季雪景",
        placeKey: "sapporo-market",
        summary: "札幌近郊温泉、雪景散步和日归入浴礼仪。",
        description:
          "适合冬季或秋季加入一晚或半日温泉休息，降低长途移动压力。",
        priceFrom: 880,
        durationHours: 6,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 72 小时可免费取消",
        rating: 4.6,
        reviewCount: 73,
        audience: "情侣,家庭,温泉爱好者",
        themes: "温泉,雪景,自然",
        startTime: "10:00",
        meetingPoint: "札幌站",
        restrictions: "纹身入浴需提前确认。",
        includes: "交通建议,温泉礼仪,散步路线",
        excludes: "巴士票,入浴费,餐饮",
        coverImage: img("photo-1519681393784-d120267933ba"),
      },
    ],
    routes: [
      {
        slug: "hokkaido-seasonal-4-days",
        title: "北海道季节风景 4 日",
        summary: "札幌市场、小樽近郊、富良野花田或定山溪温泉。",
        days: 4,
        budget: 6200,
        themes: "自然,美食,温泉",
        heroImage: img("photo-1480796927426-f609979314bd"),
        stops: "札幌,小樽,富良野,定山溪",
      },
    ],
  },
  {
    slug: "okinawa",
    name: "冲绳与那霸",
    region: "冲绳群岛",
    summary: "海岛、琉球文化、亲子海洋活动和轻松自驾，适合慢节奏假期。",
    description:
      "冲绳第一版以那霸为入口，覆盖首里、恩纳村、北部海岸和离岛前置规划。",
    season: "4-6 月和 10-11 月舒适，夏季适合海上活动但需留意台风。",
    budgetMin: 900,
    budgetMax: 2800,
    coverImage: img("photo-1507525428034-b723cf961d3e"),
    featured: false,
    places: [
      {
        key: "naha",
        name: "那霸国际通",
        type: "城市区域",
        lat: 26.2154,
        lng: 127.6792,
        address: "冲绳县那霸市牧志",
        tags: "购物,美食,交通",
        summary: "那霸市中心补给和夜间餐饮区域。",
      },
      {
        key: "onna",
        name: "恩纳村海岸",
        type: "海滩",
        lat: 26.4971,
        lng: 127.8531,
        address: "冲绳县国头郡恩纳村",
        tags: "海滩,亲子,浮潜",
        summary: "适合度假酒店、浮潜和海岸自驾。",
      },
    ],
    experiences: [
      {
        slug: "naha-ryukyu-food-night",
        title: "那霸琉球料理夜间路线",
        placeKey: "naha",
        summary: "国际通周边的冲绳料理、泡盛和夜间散步。",
        description:
          "用一晚体验苦瓜炒蛋、海葡萄、冲绳面和本地居酒屋礼仪。",
        priceFrom: 460,
        durationHours: 3,
        difficulty: "轻松",
        language: "中文",
        includesMeal: true,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.7,
        reviewCount: 82,
        audience: "朋友,情侣,美食爱好者",
        themes: "美食,文化,夜景",
        startTime: "18:30",
        meetingPoint: "牧志站",
        restrictions: "未满 20 岁不含酒精饮品。",
        includes: "向导,3 站小食,点单建议",
        excludes: "额外点单,交通",
        coverImage: img("photo-1540189549336-e6e99c3679fe"),
      },
      {
        slug: "okinawa-onna-snorkeling",
        title: "恩纳村亲子浮潜与海岸半日",
        placeKey: "onna",
        summary: "适合新手和亲子的浅水浮潜与海岸休息。",
        description:
          "包含安全说明、装备建议和天气备选方案，适合海岛行程中间日。",
        priceFrom: 720,
        durationHours: 4,
        difficulty: "中等",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 48 小时可免费取消，恶劣天气全额退改",
        rating: 4.8,
        reviewCount: 95,
        audience: "家庭,亲子,自然爱好者",
        themes: "海岛,亲子,自然",
        startTime: "09:00",
        meetingPoint: "恩纳村指定集合点",
        restrictions: "需会基础游泳，儿童年龄需提前确认。",
        includes: "装备,教练,保险说明",
        excludes: "酒店接送,餐饮",
        coverImage: img("photo-1519046904884-53103b34b206"),
      },
      {
        slug: "okinawa-north-roadtrip",
        title: "冲绳北部海岸自驾规划",
        placeKey: "onna",
        summary: "恩纳村、古宇利岛和北部景点的自驾路线规划。",
        description:
          "为租车用户规划一天动线、停车点、用餐窗口和雨天备选。",
        priceFrom: 320,
        durationHours: 2,
        difficulty: "轻松",
        language: "中文",
        includesMeal: false,
        cancellationPolicy: "出发前 24 小时可免费取消",
        rating: 4.6,
        reviewCount: 46,
        audience: "家庭,情侣,自驾",
        themes: "自驾,海岛,自然",
        startTime: "20:00",
        meetingPoint: "线上会议",
        restrictions: "不含租车预订，需自行确认国际驾照要求。",
        includes: "路线规划,停车建议,备选方案",
        excludes: "车辆,油费,门票",
        coverImage: img("photo-1500375592092-40eb2168fd21"),
      },
    ],
    routes: [
      {
        slug: "okinawa-relax-3-days",
        title: "冲绳海岛放松 3 日",
        summary: "那霸补给、恩纳村海岸和北部自驾的轻松组合。",
        days: 3,
        budget: 4300,
        themes: "海岛,亲子,自驾",
        heroImage: img("photo-1507525428034-b723cf961d3e"),
        stops: "那霸,恩纳村,古宇利岛,北部海岸",
      },
    ],
  },
];

async function main() {
  await prisma.reviewLink.deleteMany();
  await prisma.mediaAsset.deleteMany();
  await prisma.inquiry.deleteMany();
  await prisma.itineraryItem.deleteMany();
  await prisma.itineraryDay.deleteMany();
  await prisma.itinerary.deleteMany();
  await prisma.routeTemplate.deleteMany();
  await prisma.experience.deleteMany();
  await prisma.place.deleteMany();
  await prisma.destination.deleteMany();

  for (const destinationSeed of destinations) {
    const destination = await prisma.destination.create({
      data: {
        slug: destinationSeed.slug,
        name: destinationSeed.name,
        region: destinationSeed.region,
        summary: destinationSeed.summary,
        description: destinationSeed.description,
        season: destinationSeed.season,
        budgetMin: destinationSeed.budgetMin,
        budgetMax: destinationSeed.budgetMax,
        coverImage: destinationSeed.coverImage,
        featured: destinationSeed.featured,
      },
    });

    await prisma.mediaAsset.create({
      data: {
        ownerType: "destination",
        ownerId: destination.id,
        url: destination.coverImage,
        alt: `${destination.name}目的地封面`,
      },
    });

    const places = new Map<string, string>();
    for (const placeSeed of destinationSeed.places) {
      const place = await prisma.place.create({
        data: {
          destinationId: destination.id,
          name: placeSeed.name,
          type: placeSeed.type,
          lat: placeSeed.lat,
          lng: placeSeed.lng,
          address: placeSeed.address,
          tags: placeSeed.tags,
          summary: placeSeed.summary,
        },
      });
      places.set(placeSeed.key, place.id);
    }

    for (const experienceSeed of destinationSeed.experiences) {
      const experience = await prisma.experience.create({
        data: {
          destinationId: destination.id,
          placeId: places.get(experienceSeed.placeKey),
          title: experienceSeed.title,
          slug: experienceSeed.slug,
          summary: experienceSeed.summary,
          description: experienceSeed.description,
          priceFrom: experienceSeed.priceFrom,
          durationHours: experienceSeed.durationHours,
          difficulty: experienceSeed.difficulty,
          language: experienceSeed.language,
          includesMeal: experienceSeed.includesMeal,
          cancellationPolicy: experienceSeed.cancellationPolicy,
          rating: experienceSeed.rating,
          reviewCount: experienceSeed.reviewCount,
          audience: experienceSeed.audience,
          themes: experienceSeed.themes,
          startTime: experienceSeed.startTime,
          meetingPoint: experienceSeed.meetingPoint,
          restrictions: experienceSeed.restrictions,
          includes: experienceSeed.includes,
          excludes: experienceSeed.excludes,
          coverImage: experienceSeed.coverImage,
        },
      });

      await prisma.mediaAsset.create({
        data: {
          ownerType: "experience",
          ownerId: experience.id,
          url: experience.coverImage,
          alt: `${experience.title}体验图片`,
        },
      });

      await prisma.reviewLink.createMany({
        data: [
          {
            ownerType: "experience",
            ownerId: experience.id,
            provider: "Google Maps",
            rating: experience.rating,
            url: `https://www.google.com/search?q=${encodeURIComponent(
              `${experience.title} 日本 评价`,
            )}`,
          },
          {
            ownerType: "experience",
            ownerId: experience.id,
            provider: "Tripadvisor",
            rating: Math.max(4.2, experience.rating - 0.1),
            url: `https://www.tripadvisor.com/Search?q=${encodeURIComponent(
              experience.title,
            )}`,
          },
        ],
      });
    }

    for (const routeSeed of destinationSeed.routes) {
      await prisma.routeTemplate.create({
        data: {
          destinationId: destination.id,
          title: routeSeed.title,
          slug: routeSeed.slug,
          summary: routeSeed.summary,
          days: routeSeed.days,
          budget: routeSeed.budget,
          themes: routeSeed.themes,
          heroImage: routeSeed.heroImage,
          stops: routeSeed.stops,
        },
      });
    }
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
